kind: Service
apiVersion: v1
metadata:
  name: product-test-api-service
  namespace: test-local
spec:
  selector:
    app:  product-test-api
  ports:
    - protocol: TCP
      port: 9000
      targetPort: 80
  type: NodePort
